### ISSUE TITLE
Не могу получить валидный токен: ValueError: Неверный хеш, попробуйте еще раз

### ISSUE THREAD

**Issue by slavatulaev** [kesha1225/tonplaceApi#2]
Авторизация сессии в телеге проходит, а после скрипт выдает ValueError: Неверный хеш, попробуйте еще раз
есть идеи как бороться?

**Comment by kesha1225** [comment]
Возможно стоит чуть больше подождать после подтверждения, добавлю сейчас более точное отображение ошибок
